spring:
  application:
    name: admin-server
server:
  port: 8769
eureka:
  client:
    service-url:
      defaultZone: http://zhangchen:zhangchen@localhost:8761/eureka/
    healthcheck:
      enabled: true
# management:?
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
