server:
  port: 8763

spring:
  application:
    name: service-hi
eureka:
  client:
    service-url:
      defaultZone: http://zhangchen:zhangchen@localhost:8761/eureka/
    healthcheck:
      enabled: true

# actuator 暴露端点设置
management:
  endpoints:
    web:
      exposure:
        # 暴露端点
        include: '*'
        # 不公开端点
        exclude: env,beans