
# eureka.client.registerWithEureka ：表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
# eureka.client.fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
# eureka.client.serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # 无认证服务时：
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 有认证服务后：（client需要同步修改）
      defaultZone: http://zhangchen:zhangchen@localhost:8761/eureka/
      #当认证服务无效时，检查security包是否导入完整
spring:
  application:
    name: eureka-server

  security:
    user:
      name: 'zhangchen'
      password: 'zhangchen'


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS