server:
  port: 8762

spring:
  application:
    name: service-hi
# admin
  boot:
    admin:
      client:
        url: http://localhost:8769

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
# 带登录控制的 eureka
eureka:
  client:
    service-url:
      defaultZone: http://zhangchen:zhangchen@localhost:8761/eureka/
